apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: fields.archframework.volnenko.ru
spec:
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                code:
                  type: string
                name:
                  type: string
                description:
                  type: string
  scope: Namespaced
  group: archframework.volnenko.ru
  names:
    kind: Field
    listKind: FieldList
    singular: field
    plural: fields